name: Get Raw Data

on:
  schedule:
    - cron: 0 20 * * 1-6

jobs:
  updateData:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get yesterday's date
      id: ydate
      run: echo "::set-output name=ydate::$(date -d "yesterday 22:0" +'%Y-%m-%d')"

    - name: Get data
      run:  curl https://santemontreal.qc.ca/fileadmin/fichiers/Campagnes/coronavirus/situation-montreal/municipal.csv > rawdata/${{ steps.ydate.outputs.ydate }}.csv

    - name: Push data
      run: |
        git config --global user.name 'fredericharnois'
        git config --global user.email 'fredericharnois@users.noreply.github.com'
        git add *.csv
        git commit -am 'Added raw data for ${{ steps.ydate.outputs.ydate }}'
        git push
