name: py

on:
  schedule:
    - cron: 0 22 * * 1-5

jobs:
  updateData:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate file
      run: app.py

    - name: Get yesterday's date
      id: ydate
      run: echo "set-output name=ydate::$(date -d "yesterday 22:0" +'%Y-%m-%d')"
    
    - name: Update data
      run: |
        git config --global user.name 'fredericharnois'
        git config --global user.email 'fredericharnois@users.noreply.github.com'
        git commit -am "Added data for ${{ steps.ydate.outputs.ydate }}"
        git push
